parameters:
    question_templates:
        bot_screen:
            template: question.html.twig
            next: online_chat
            info:
                title: AI is here to help you, ask something!
                content:
                    - The simplest user experience is an inteligent and intuitive ‘bot’ available via a messenger interface.
                action: select a message
                action_css_class: left
            css_class: bot-screen
        online_chat:
            template: question.html.twig
            next: laptop
            info:
                title: Try AI web assistance!
                content:
                    - The use of AI reduces human error and provides amazing customer experience to resolve simple customer problems or queries
                action: select a message
                action_css_class: right
            css_class: web-chat-screen
        laptop:
            template: question.html.twig
            next: desktop
            info:
                title: AI is here to help you, ask something!
                content:
                    - The simplest user experience is an inteligent and intuitive 'bot' available via a mesenger interface.
                action: select a message
                action_css_class: left
            css_class: laptop-screen
        desktop:
            template: question.html.twig
            next: bot_screen
            info:
                title: AI is here to help you, ask something!
                content:
                    - The simplest user experience is an inteligent and intuitive 'bot' available via a mesenger interface.
                action: select a message
                action_css_class: right
            css_class: desktop-screen
